module.exports = {
  LendingPool: 'LendingPool',
  Lenders: 'Lenders',
  TokenCollateralLoans: 'TokenCollateralLoans',
  EtherCollateralLoans: 'EtherCollateralLoans',
  LoanTermsConsensus: 'LoanTermsConsensus',
  InterestConsensus: 'InterestConsensus',
  EscrowFactory: 'EscrowFactory',
  Escrow: 'Escrow',
  ChainlinkAggregator: 'ChainlinkAggregator',
  Settings: 'Settings',
  LogicVersionsRegistry: 'LogicVersionsRegistry',
  TTokenRegistry: 'TTokenRegistry',
  ATMFactory: 'ATMFactory',
  ATMSettings: 'ATMSettings',
  ATMGovernance: 'ATMGovernance',
  TLRToken: 'TLRToken',
  ATMLiquidityMining: 'ATMLiquidityMining',
  MarketFactory: 'MarketFactory',
  Uniswap: 'Uniswap',
  Compound: 'Compound',
};
