module.exports = {
    TToken: 'TToken',
    LendingPool: 'LendingPool',
    TokenCollateralLoans: 'TokenCollateralLoans',
    EtherCollateralLoans: 'EtherCollateralLoans',
    LoanTermsConsensus: 'LoanTermsConsensus',
    EscrowFactory: 'EscrowFactory',
    Escrow: 'Escrow',
    ChainlinkAggregator: 'ChainlinkAggregator',
    Settings: 'Settings',
    LogicVersionsRegistry: 'LogicVersionsRegistry',
    ATMFactory: 'ATMFactory',
    ATMSettings: 'ATMSettings',
    ATMGovernance: 'ATMGovernance',
    TLRToken: 'TLRToken',
    ATMLiquidityMining: 'ATMLiquidityMining',
    MarketFactory: 'MarketFactory',
    Uniswap: 'Uniswap',
    Compound: 'Compound'
}
