module.exports = {
    LendingPool: 'LendingPool',
    Lenders: 'Lenders',
    TokenCollateralLoans: 'TokenCollateralLoans',
    EtherCollateralLoans: 'EtherCollateralLoans',
    LoanTermsConsensus: 'LoanTermsConsensus',
    InterestConsensus: 'InterestConsensus',
    EscrowFactory: 'EscrowFactory',
    Escrow: 'Escrow',
    ChainlinkPairAggregator: 'ChainlinkPairAggregator',
    ChainlinkPairAggregatorRegistry: 'ChainlinkPairAggregatorRegistry',
    Settings: 'Settings',
    LogicVersionsRegistry: 'LogicVersionsRegistry',
    MarketsState: 'MarketsState',
    ATMFactory: 'ATMFactory',
    ATMSettings: 'ATMSettings',
    ATMGovernance: 'ATMGovernance',
    ATMToken: 'ATMToken',
}
