const { DUMMY_NODE_COMPONENT_VERSION } = require('../../consts');

module.exports = {
    WEB2: DUMMY_NODE_COMPONENT_VERSION,
    EVENT_LISTENER: DUMMY_NODE_COMPONENT_VERSION,
    POSTGRES: DUMMY_NODE_COMPONENT_VERSION,
    REDIS: DUMMY_NODE_COMPONENT_VERSION
}