const { INITIAL_NODE_COMPONENT_VERSION } = require('../../consts');

module.exports = {
    WEB2: INITIAL_NODE_COMPONENT_VERSION,
    EVENT_LISTENER: INITIAL_NODE_COMPONENT_VERSION,
    POSTGRES: INITIAL_NODE_COMPONENT_VERSION,
    REDIS: INITIAL_NODE_COMPONENT_VERSION
}